### ISSUE TITLE
There's no "kcanonca_reg_ver2" file

### ISSUE THREAD

**Issue by TenderRainMT** [glisanti/KCCAReId#2]
I want to run your code, but there's no "kcanonca_reg_ver2" file. Would you like to provide the file to me?Thank you very much!

**Comment by iacopomasi** [comment]
Hi @TenderRainMT,
we do not provide that code because we do not own the copyright. You should read the instructions here: https://github.com/glisanti/KCCAReId/blob/master/README.md#requirements


Also, please consider that there is a better method https://github.com/glisanti/MCK-CCA

I hope this helps.
